var a;a||(a=typeof Module !== 'undefined' ? Module : {});var h={},l;for(l in a)a.hasOwnProperty(l)&&(h[l]=a[l]);var m="";document.currentScript&&(m=document.currentScript.src);m=0!==m.indexOf("blob:")?m.substr(0,m.lastIndexOf("/")+1):"";var n=a.print||console.log.bind(console),p=a.printErr||console.warn.bind(console);for(l in h)h.hasOwnProperty(l)&&(a[l]=h[l]);h=null;var t;a.wasmBinary&&(t=a.wasmBinary);"object"!==typeof WebAssembly&&p("no native wasm support detected");
var v,ca=new WebAssembly.Table({initial:6,maximum:6,element:"anyfunc"}),w=!1,x="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");var y,z,A,C=a.TOTAL_MEMORY||16777216;a.wasmMemory?v=a.wasmMemory:v=new WebAssembly.Memory({initial:C/65536,maximum:C/65536});v&&(y=v.buffer);C=y.byteLength;var D=y;y=D;a.HEAP8=new Int8Array(D);a.HEAP16=new Int16Array(D);a.HEAP32=A=new Int32Array(D);a.HEAPU8=z=new Uint8Array(D);a.HEAPU16=new Uint16Array(D);
a.HEAPU32=new Uint32Array(D);a.HEAPF32=new Float32Array(D);a.HEAPF64=new Float64Array(D);A[792]=5246208;function E(b){for(;0<b.length;){var c=b.shift();if("function"==typeof c)c();else{var e=c.j;"number"===typeof e?void 0===c.i?a.dynCall_v(e):a.dynCall_vi(e,c.i):e(void 0===c.i?null:c.i)}}}var F=[],G=[],da=[],H=[];function ea(){var b=a.preRun.shift();F.unshift(b)}var N=0,O=null,P=null;a.preloadedImages={};a.preloadedAudios={};
function Q(b){if(a.onAbort)a.onAbort(b);n(b);p(b);w=!0;throw new WebAssembly.RuntimeError("abort("+b+"). Build with -s ASSERTIONS=1 for more info.");}function R(){var b=S;return String.prototype.startsWith?b.startsWith("data:application/octet-stream;base64,"):0===b.indexOf("data:application/octet-stream;base64,")}var S="secp256k1.wasm";if(!R()){var T=S;S=a.locateFile?a.locateFile(T,m):m+T}
function U(){try{if(t)return new Uint8Array(t);throw"both async and sync fetching of the wasm failed";}catch(b){Q(b)}}function fa(){return t||"function"!==typeof fetch?new Promise(function(b){b(U())}):fetch(S,{credentials:"same-origin"}).then(function(b){if(!b.ok)throw"failed to load wasm binary file at '"+S+"'";return b.arrayBuffer()}).catch(function(){return U()})}G.push({j:function(){V()}});
var ha=[null,[],[]],ia={b:function(){Q()},d:function(b,c,e){z.set(z.subarray(c,c+e),b)},e:function(){Q("OOM")},f:function(){return 0},c:function(){return 0},a:function(b,c,e,B){try{for(var d=0,f=0;f<e;f++){for(var ja=A[c+8*f>>2],Y=A[c+(8*f+4)>>2],I=0;I<Y;I++){var J=z[ja+I],K=ha[b];if(0===J||10===J){for(var q=K,k=0,r=k+NaN,u=k;q[u]&&!(u>=r);)++u;if(16<u-k&&q.subarray&&x)var Z=x.decode(q.subarray(k,u));else{for(r="";k<u;){var g=q[k++];if(g&128){var L=q[k++]&63;if(192==(g&224))r+=String.fromCharCode((g&
31)<<6|L);else{var aa=q[k++]&63;g=224==(g&240)?(g&15)<<12|L<<6|aa:(g&7)<<18|L<<12|aa<<6|q[k++]&63;if(65536>g)r+=String.fromCharCode(g);else{var ba=g-65536;r+=String.fromCharCode(55296|ba>>10,56320|ba&1023)}}}else r+=String.fromCharCode(g)}Z=r}(1===b?n:p)(Z);K.length=0}else K.push(J)}d+=Y}A[B>>2]=d;return 0}catch(M){return"undefined"!==typeof FS&&M instanceof FS.l||Q(M),M.m}},memory:v,table:ca},ka=function(){function b(d){a.asm=d.exports;N--;a.monitorRunDependencies&&a.monitorRunDependencies(N);0==
N&&(null!==O&&(clearInterval(O),O=null),P&&(d=P,P=null,d()))}function c(d){b(d.instance)}function e(d){return fa().then(function(f){return WebAssembly.instantiate(f,B)}).then(d,function(f){p("failed to asynchronously prepare wasm: "+f);Q(f)})}var B={a:ia};N++;a.monitorRunDependencies&&a.monitorRunDependencies(N);if(a.instantiateWasm)try{return a.instantiateWasm(B,b)}catch(d){return p("Module.instantiateWasm callback failed with error: "+d),!1}(function(){if(t||"function"!==typeof WebAssembly.instantiateStreaming||
R()||"function"!==typeof fetch)return e(c);fetch(S,{credentials:"same-origin"}).then(function(d){return WebAssembly.instantiateStreaming(d,B).then(c,function(f){p("wasm streaming compile failed: "+f);p("falling back to ArrayBuffer instantiation");e(c)})})})();return{}}();a.asm=ka;var V=a.___wasm_call_ctors=function(){return(V=a.___wasm_call_ctors=a.asm.g).apply(null,arguments)};a._wasm_secp256k1_ec_pubkey_create=function(){return(a._wasm_secp256k1_ec_pubkey_create=a.asm.h).apply(null,arguments)};
a.asm=ka;var W;P=function la(){W||X();W||(P=la)};
function X(){function b(){if(!W&&(W=!0,!w)){E(G);E(da);if(a.onRuntimeInitialized)a.onRuntimeInitialized();if(a.postRun)for("function"==typeof a.postRun&&(a.postRun=[a.postRun]);a.postRun.length;){var c=a.postRun.shift();H.unshift(c)}E(H)}}if(!(0<N)){if(a.preRun)for("function"==typeof a.preRun&&(a.preRun=[a.preRun]);a.preRun.length;)ea();E(F);0<N||(a.setStatus?(a.setStatus("Running..."),setTimeout(function(){setTimeout(function(){a.setStatus("")},1);b()},1)):b())}}a.run=X;
if(a.preInit)for("function"==typeof a.preInit&&(a.preInit=[a.preInit]);0<a.preInit.length;)a.preInit.pop()();X();
